const TAX_BANDS = [{ amount: 800000, rate: 0 }, { amount: 2200000, rate: .15 }, { amount: 9000000, rate: .18 }, { amount: 13000000, rate: .21 }, { amount: 25000000, rate: .23 }, { amount: Infinity, rate: .25 }];
const employeeKey = 'tax-cup-employees';
const runKey = 'tax-cup-payroll-runs';
const $ = (id) => document.getElementById(id);
const number = (value) => Number(value) || 0;
const money = (value) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(Math.max(0, value || 0));
const load = (key) => JSON.parse(localStorage.getItem(key) || '[]');
const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
let employees = load(employeeKey);
let runs = load(runKey);

function tax(income) { let remaining = Math.max(0, income); let total = 0; for (const band of TAX_BANDS) { const portion = Math.min(remaining, band.amount); if (portion <= 0) break; total += portion * band.rate; remaining -= portion; } return total; }
function settings() { return Object.fromEntries([...document.querySelectorAll('.allocation')].map((input) => [input.dataset.key, Math.max(0, number(input.value))])); }
function allocationValid() { const total = Object.values(settings()).reduce((sum, value) => sum + value, 0); $('allocation-total').textContent = `${total.toFixed(2).replace(/\.00$/, '')}%`; const valid = Math.abs(total - 100) < .005; $('allocation-status').textContent = valid ? 'Ready' : `${Math.abs(100 - total).toFixed(2)}% ${total < 100 ? 'remaining' : 'over'}`; $('allocation-status').classList.toggle('invalid', !valid); return valid; }
function calculate(employee) { const parts = settings(); const basic = employee.salary * parts.basic / 100; const housing = employee.salary * parts.housing / 100; const transport = employee.salary * parts.transport / 100; const other = employee.salary * parts.other / 100; const pension = $('shared-pension').checked ? (basic + housing + transport) * .08 : 0; const nhf = $('shared-nhf').checked ? basic * .025 : 0; const rentRelief = Math.min(number($('shared-rent').value) * .2, 500000); const paye = tax(Math.max(0, employee.salary * 12 - (pension + nhf) * 12 - rentRelief)) / 12; return { basic, housing, transport, other, paye, pension, nhf, net: Math.max(0, employee.salary - paye - pension - nhf) }; }
function currentResults() { return employees.map((employee) => ({ employee, result: calculate(employee) })); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character])); }
function render() { const results = allocationValid() ? currentResults() : []; $('employee-count').textContent = employees.length; $('run-count').textContent = runs.length; $('gross-total').textContent = money(employees.reduce((total, employee) => total + number(employee.salary), 0)); $('paye-total').textContent = money(results.reduce((total, item) => total + item.result.paye, 0)); $('net-total').textContent = money(results.reduce((total, item) => total + item.result.net, 0)); $('empty-message').classList.toggle('hidden', employees.length > 0); $('payroll-empty').classList.toggle('hidden', results.length > 0); $('run-empty').classList.toggle('hidden', runs.length > 0); $('directory').innerHTML = employees.map((employee) => `<div class="directory-row"><span><strong>${escapeHtml(employee.name)}</strong><small>${escapeHtml(employee.role || 'Employee')}</small></span><b>${money(employee.salary)}</b><button class="remove-button" data-id="${employee.id}" title="Remove employee">×</button></div>`).join(''); $('payroll-body').innerHTML = results.map(({ employee, result }) => `<tr><td>${escapeHtml(employee.name)}</td><td>${money(employee.salary)}</td><td>${money(result.basic)}</td><td>${money(result.housing)}</td><td>${money(result.transport)}</td><td>${money(result.other)}</td><td>${money(result.paye)}</td><td>${money(result.pension)}</td><td>${money(result.nhf)}</td><td><strong>${money(result.net)}</strong></td></tr>`).join(''); $('run-list').innerHTML = runs.slice().reverse().map((run) => `<div class="run-row"><span><strong>${run.date}</strong><small>${run.count} employees</small></span><b>${money(run.total)}</b></div>`).join(''); document.querySelectorAll('.remove-button').forEach((button) => button.addEventListener('click', () => { employees = employees.filter((employee) => employee.id !== Number(button.dataset.id)); save(employeeKey, employees); render(); })); }

$('add-employee').addEventListener('click', () => { $('employee-form').classList.toggle('hidden'); $('employee-name').focus(); });
$('save-employee').addEventListener('click', () => { const name = $('employee-name').value.trim(); if (!name) return; employees.push({ id: Date.now(), name, role: $('employee-role').value.trim(), salary: number($('employee-salary').value) }); save(employeeKey, employees); ['employee-name', 'employee-role', 'employee-salary'].forEach((id) => { $(id).value = ''; }); $('employee-form').classList.add('hidden'); render(); });
$('save-run').addEventListener('click', () => { const results = currentResults(); if (!employees.length || !allocationValid()) return; runs.push({ date: new Date().toLocaleDateString('en-NG', { year: 'numeric', month: 'short', day: 'numeric' }), count: employees.length, total: results.reduce((sum, item) => sum + item.result.net, 0) }); save(runKey, runs); render(); });
$('print').addEventListener('click', () => window.print());
document.querySelectorAll('.allocation').forEach((input) => input.addEventListener('input', render));
$('shared-rent').addEventListener('input', render);
$('shared-pension').addEventListener('change', render);
$('shared-nhf').addEventListener('change', render);
render();