const loginUsers = () => { try { const users = JSON.parse(localStorage.getItem('tax-cup-users') || '[]'); return Array.isArray(users) ? users : []; } catch (error) { return []; } };
async function hashPassword(value) { const data = new TextEncoder().encode(value); const hash = await crypto.subtle.digest('SHA-256', data); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
const demoUser = { id: 'USR-ADMIN', name: 'Demo administrator', email: 'admin@taxcup.local', department: 'Finance', title: 'System administrator', role: 'Super Administrator', passwordHash: '41bd876b085d6031cb0e04de35b88d77f83a4ba39f879fee40805ac19e356023', active: true, createdAt: new Date().toISOString() };
const storedUsers = loginUsers();
if (!storedUsers.some((user) => user.id === demoUser.id && user.passwordHash && user.email)) localStorage.setItem('tax-cup-users', JSON.stringify([demoUser, ...storedUsers.filter((user) => user.id !== demoUser.id)]));
const form = document.getElementById('login-form');
const requestedPage = new URLSearchParams(window.location.search).get('redirect');
const allowedPages = new Set(['index.html', 'employees.html', 'company.html', 'payroll.html']);
const redirectAfterLogin = allowedPages.has(requestedPage) ? requestedPage : 'index.html';
form.addEventListener('submit', async (event) => { event.preventDefault(); const email = document.getElementById('login-email').value.trim().toLowerCase(); const passwordHash = await hashPassword(document.getElementById('login-password').value); const user = loginUsers().find((item) => item.email === email && item.active && item.passwordHash === passwordHash); if (!user) { document.getElementById('login-error').textContent = 'The email or password is incorrect, or the account is inactive.'; return; } localStorage.setItem('tax-cup-current-role', user.role); localStorage.setItem('tax-cup-current-user', JSON.stringify({ id: user.id, name: user.name, email: user.email, role: user.role })); user.lastActivity = new Date().toISOString(); localStorage.setItem('tax-cup-users', JSON.stringify(loginUsers().map((item) => item.id === user.id ? user : item))); window.location.href = redirectAfterLogin; });