const EMPLOYEE_KEY = 'tax-cup-employees';
const RECORD_KEY = 'tax-cup-salary-records';
const USER_KEY = 'tax-cup-users';
const AUDIT_KEY = 'tax-cup-audit';
const $ = (id) => document.getElementById(id);
const number = (value) => Math.max(0, Number(value) || 0);
const money = (value) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(number(value));
const read = (key, fallback = []) => { try { const value = JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); return Array.isArray(value) ? value : fallback; } catch (error) { return fallback; } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const todayMonth = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; };
const employeeList = () => read(EMPLOYEE_KEY).map((employee, index) => ({ id: String(employee.id ?? index + 1), name: employee.name || 'Unnamed employee', department: employee.department || employee.role || 'General', title: employee.title || employee.role || 'Employee', status: employee.status || 'Active', salary: number(employee.salary) }));
let employees = employeeList();
let records = read(RECORD_KEY);
let users = read(USER_KEY);
let audit = read(AUDIT_KEY);
let editingRecordId = null;
const currentUser = JSON.parse(localStorage.getItem('tax-cup-current-user') || 'null');
let currentRole = localStorage.getItem('tax-cup-current-role') || currentUser?.role || 'Super Administrator';

const roles = { 'Super Administrator': ['all'], 'HR Manager': ['viewEmployees', 'viewPayroll', 'viewReports'], Accountant: ['viewEmployees', 'viewPayroll', 'createPayroll', 'editPayroll', 'approvePayroll', 'viewReports', 'exportReports'], 'Payroll Officer': ['viewEmployees', 'viewPayroll', 'createPayroll', 'editPayroll', 'viewReports', 'exportReports'], Management: ['viewReports'] };
const can = (permission) => (roles[currentRole] || []).includes('all') || (roles[currentRole] || []).includes(permission);
const addAudit = (action, affected, change = '') => { audit.unshift({ id: Date.now(), at: new Date().toISOString(), user: $('session-user').textContent, action, affected, change }); write(AUDIT_KEY, audit.slice(0, 300)); };

function totalEarnings(record) { return ['basic', 'housing', 'transport', 'meal', 'utility', 'otherAllowances', 'bonus', 'overtime', 'commission', 'arrears', 'otherEarnings'].reduce((sum, key) => sum + number(record[key]), 0); }
function totalDeductions(record) { return ['paye', 'pension', 'nhf', 'nsitf', 'loan', 'advance', 'absence', 'otherDeductions'].reduce((sum, key) => sum + number(record[key]), 0); }
function hydrateRecord(record) { const employee = employees.find((item) => item.id === String(record.employeeId)); return { ...record, employeeName: record.employeeName || employee?.name || 'Former employee', department: record.department || employee?.department || 'General', title: record.title || employee?.title || 'Employee', gross: totalEarnings(record), deductions: totalDeductions(record), net: Math.max(0, totalEarnings(record) - totalDeductions(record)) }; }
function filteredRecords(period = '', department = '') { return records.map(hydrateRecord).filter((record) => (!period || record.period === period) && (!department || record.department === department)); }
function populateSelects() { const departments = [...new Set(employees.map((employee) => employee.department))].sort(); const employeeOptions = employees.map((employee) => `<option value="${escapeHtml(employee.id)}">${escapeHtml(employee.name)} (${escapeHtml(employee.id)})</option>`).join(''); document.querySelectorAll('#record-employee,#report-employee,#form-employee').forEach((select) => { const first = select.options[0]?.outerHTML || ''; select.innerHTML = first + employeeOptions; }); document.querySelectorAll('#dashboard-department,#record-department,#company-department').forEach((select) => { const first = select.options[0]?.outerHTML || ''; select.innerHTML = first + departments.map((department) => `<option>${escapeHtml(department)}</option>`).join(''); }); }
function renderDashboard() { const period = $('dashboard-period').value; const department = $('dashboard-department').value; const selected = filteredRecords(period, department); const gross = selected.reduce((sum, record) => sum + record.gross, 0); const deductions = selected.reduce((sum, record) => sum + record.deductions, 0); const paid = selected.filter((record) => record.paymentStatus === 'Paid').length; $('metric-employees').textContent = employees.length; $('metric-paid').textContent = paid; $('metric-paid-note').textContent = `of ${selected.length} records`; $('metric-gross').textContent = money(gross); $('metric-net').textContent = money(gross - deductions); $('metric-deductions').textContent = money(deductions); $('metric-pending').textContent = selected.filter((record) => record.paymentStatus !== 'Paid').length; const months = [...new Set(records.map((record) => record.period))].sort().slice(-6); $('trend-chart').innerHTML = months.length ? months.map((month) => { const monthRecords = filteredRecords(month, department); const max = Math.max(gross, 1); const monthGross = monthRecords.reduce((sum, record) => sum + record.gross, 0); const monthNet = monthRecords.reduce((sum, record) => sum + record.net, 0); return `<div class="trend-column"><div class="trend-bars"><i style="height:${Math.max(4, monthGross / max * 100)}%"></i><b style="height:${Math.max(4, monthNet / max * 100)}%"></b></div><small>${escapeHtml(month)}</small></div>`; }).join('') : '<p class="empty-message">Save monthly records to see a trend.</p>'; const statuses = ['Paid', 'Pending', 'Failed']; $('status-chart').innerHTML = statuses.map((status) => `<div class="status-row"><span><i class="status-dot ${status.toLowerCase()}"></i>${status}</span><strong>${selected.filter((record) => record.paymentStatus === status).length}</strong></div>`).join(''); const byDepartment = [...new Set(selected.map((record) => record.department))].map((departmentName) => [departmentName, selected.filter((record) => record.department === departmentName).reduce((sum, record) => sum + record.gross, 0)]); const departmentMax = Math.max(...byDepartment.map((item) => item[1]), 1); $('department-chart').innerHTML = byDepartment.length ? byDepartment.map(([departmentName, amount]) => `<div class="bar-row"><span>${escapeHtml(departmentName)}</span><i><b style="width:${amount / departmentMax * 100}%"></b></i><strong>${money(amount)}</strong></div>`).join('') : '<p class="empty-message">No departmental data.</p>'; const deductionKeys = [['paye', 'PAYE'], ['pension', 'Pension'], ['nhf', 'NHF'], ['loan', 'Loans'], ['otherDeductions', 'Other']]; $('deduction-chart').innerHTML = deductionKeys.map(([key, label]) => `<div class="bar-row"><span>${label}</span><i><b style="width:${Math.min(100, selected.reduce((sum, record) => sum + number(record[key]), 0) / Math.max(deductions, 1) * 100)}%"></b></i><strong>${money(selected.reduce((sum, record) => sum + number(record[key]), 0))}</strong></div>`).join(''); }
function recordMatches(record) { const query = $('record-search').value.trim().toLowerCase(); const from = $('record-from').value; const to = $('record-to').value; return (!query || [record.employeeName, record.employeeId, record.department, record.title].some((value) => String(value).toLowerCase().includes(query))) && (!from || record.period >= from) && (!to || record.period <= to) && (!$('record-employee').value || record.employeeId === $('record-employee').value) && (!$('record-department').value || record.department === $('record-department').value) && (!$('record-status').value || record.workflowStatus === $('record-status').value) && (!$('record-payment').value || record.paymentStatus === $('record-payment').value); }
function renderRecords() { const matches = records.map(hydrateRecord).filter(recordMatches); $('records-body').innerHTML = matches.map((record) => `<tr><td><strong>${escapeHtml(record.period)}</strong></td><td>${escapeHtml(record.employeeName)}<small>${escapeHtml(record.employeeId)}</small></td><td>${escapeHtml(record.department)}</td><td>${money(record.gross)}</td><td>${money(record.deductions)}</td><td><strong>${money(record.net)}</strong></td><td><span class="pill workflow-${record.workflowStatus.toLowerCase().replaceAll(' ', '-')}">${escapeHtml(record.workflowStatus)}</span></td><td><span class="pill payment-${record.paymentStatus.toLowerCase()}">${escapeHtml(record.paymentStatus)}</span></td><td><button class="table-action" data-edit-record-id="${record.id}">Edit</button> <button class="table-action" data-record-id="${record.id}">Advance</button></td></tr>`).join(''); $('records-empty').classList.toggle('hidden', matches.length > 0); document.querySelectorAll('[data-record-id]').forEach((button) => button.addEventListener('click', () => advanceRecord(button.dataset.recordId))); document.querySelectorAll('[data-edit-record-id]').forEach((button) => button.addEventListener('click', () => openRecord(records.find((record) => record.id === button.dataset.editRecordId)))); }
function renderEmployeeReport() { const employeeId = $('report-employee').value; const from = $('report-from').value; const to = $('report-to').value; const output = $('employee-report-output'); if (!employeeId) { output.innerHTML = '<p class="empty-message">Select an employee to generate a report.</p>'; return; } const employee = employees.find((item) => item.id === employeeId); const selected = records.map(hydrateRecord).filter((record) => record.employeeId === employeeId && (!from || record.period >= from) && (!to || record.period <= to)); const totals = selected.reduce((sum, record) => ({ gross: sum.gross + record.gross, deductions: sum.deductions + record.deductions, net: sum.net + record.net }), { gross: 0, deductions: 0, net: 0 }); output.innerHTML = `<div class="profile-header"><div><p class="kicker">Employee profile</p><h3>${escapeHtml(employee?.name || 'Former employee')}</h3><span>${escapeHtml(employee?.id || employeeId)} / ${escapeHtml(employee?.department || 'General')} / ${escapeHtml(employee?.title || 'Employee')}</span></div><div class="profile-total"><small>Total net pay</small><strong>${money(totals.net)}</strong></div></div><div class="summary-grid compact-summary"><div><span>Records</span><strong>${selected.length}</strong></div><div><span>Gross earnings</span><strong>${money(totals.gross)}</strong></div><div><span>Deductions</span><strong>${money(totals.deductions)}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Month</th><th>Basic</th><th>Allowances</th><th>Bonus / overtime</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Payment</th></tr></thead><tbody>${selected.sort((a, b) => b.period.localeCompare(a.period)).map((record) => `<tr><td>${record.period}</td><td>${money(record.basic)}</td><td>${money(record.gross - record.basic - record.bonus - record.overtime - record.commission - record.arrears - record.otherEarnings)}</td><td>${money(record.bonus + record.overtime + record.commission)}</td><td>${money(record.gross)}</td><td>${money(record.deductions)}</td><td><strong>${money(record.net)}</strong></td><td>${escapeHtml(record.paymentStatus)}</td></tr>`).join('')}</tbody></table></div>`; }
function companySelection() { return filteredRecords($('company-period').value, $('company-department').value); }
function renderCompanyReport() { const selected = companySelection(); const totals = selected.reduce((sum, record) => ({ basic: sum.basic + record.basic, allowances: sum.allowances + record.gross - record.basic - record.bonus - record.overtime - record.commission - record.arrears - record.otherEarnings, bonus: sum.bonus + record.bonus, overtime: sum.overtime + record.overtime, gross: sum.gross + record.gross, deductions: sum.deductions + record.deductions, net: sum.net + record.net }), { basic: 0, allowances: 0, bonus: 0, overtime: 0, gross: 0, deductions: 0, net: 0 }); $('company-summary').innerHTML = [['Employees', selected.length], ['Basic salary', money(totals.basic)], ['Allowances', money(totals.allowances)], ['Bonuses', money(totals.bonus)], ['Overtime', money(totals.overtime)], ['Gross payroll', money(totals.gross)], ['Total deductions', money(totals.deductions)], ['Net payable', money(totals.net)]].map(([label, value]) => `<div><span>${label}</span><strong>${value}</strong></div>`).join(''); $('company-body').innerHTML = selected.map((record) => `<tr><td>${escapeHtml(record.employeeName)}<small>${escapeHtml(record.employeeId)}</small></td><td>${escapeHtml(record.department)}</td><td>${money(record.basic)}</td><td>${money(record.gross - record.basic - record.bonus - record.overtime - record.commission - record.arrears - record.otherEarnings)}</td><td>${money(record.bonus)}</td><td>${money(record.overtime)}</td><td>${money(record.gross)}</td><td>${money(record.deductions)}</td><td><strong>${money(record.net)}</strong></td></tr>`).join(''); }
function renderUsers() { $('users-body').innerHTML = users.map((user) => `<tr><td><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></td><td>${escapeHtml(user.department || '—')}</td><td>${escapeHtml(user.role)}</td><td><span class="pill ${user.active ? 'payment-paid' : 'payment-failed'}">${user.active ? 'Active' : 'Inactive'}</span></td><td>${user.lastActivity ? new Date(user.lastActivity).toLocaleString('en-NG') : 'Never'}</td><td><button class="table-action" data-user-id="${user.id}">${user.active ? 'Deactivate' : 'Activate'}</button></td></tr>`).join(''); document.querySelectorAll('[data-user-id]').forEach((button) => button.addEventListener('click', () => { const user = users.find((item) => String(item.id) === button.dataset.userId); if (user) { user.active = !user.active; write(USER_KEY, users); addAudit(user.active ? 'Activated user' : 'Deactivated user', user.email); renderUsers(); renderAudit(); } })); }
function renderAudit() { $('audit-body').innerHTML = audit.map((event) => `<tr><td>${new Date(event.at).toLocaleString('en-NG')}</td><td>${escapeHtml(event.user)}</td><td>${escapeHtml(event.action)}</td><td>${escapeHtml(event.affected)}</td><td>${escapeHtml(event.change || '—')}</td></tr>`).join(''); }
function openRecord(record = null) { if (!can(record ? 'editPayroll' : 'createPayroll')) return alert('Your role is not allowed to change payroll records.'); editingRecordId = record?.id || null; $('record-modal-title').textContent = record ? 'Edit payroll snapshot' : 'Record monthly payroll'; $('record-form').reset(); $('form-period').value = record?.period || todayMonth(); if (record) Object.entries(record).forEach(([key, value]) => { const field = $(`form-${key}`); if (field) field.value = value; }); $('record-modal').classList.remove('hidden'); updateFormTotals(); }
function formField(key) { return $(`form-${key.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`)}`); }
function formRecord() { const employee = employees.find((item) => item.id === $('form-employee').value); const keys = ['basic', 'housing', 'transport', 'meal', 'utility', 'otherAllowances', 'bonus', 'overtime', 'commission', 'arrears', 'otherEarnings', 'paye', 'pension', 'nhf', 'nsitf', 'loan', 'advance', 'absence', 'otherDeductions']; const record = { employeeId: employee?.id, employeeName: employee?.name, department: employee?.department, title: employee?.title, period: $('form-period').value, workflowStatus: editingRecordId ? (records.find((item) => item.id === editingRecordId)?.workflowStatus || 'Draft') : 'Draft', paymentStatus: $('form-payment').value, paymentDate: $('form-payment-date').value, reference: $('form-reference').value.trim(), remarks: $('form-remarks').value.trim() }; keys.forEach((key) => { record[key] = number(formField(key).value); }); return record; }
function updateFormTotals() { const record = formRecord(); $('form-gross').textContent = money(totalEarnings(record)); $('form-total-deductions').textContent = money(totalDeductions(record)); $('form-net').textContent = money(totalEarnings(record) - totalDeductions(record)); }
function saveRecord(event) { event.preventDefault(); if (!can(editingRecordId ? 'editPayroll' : 'createPayroll')) return; const record = formRecord(); if (!record.employeeId || !record.period || record.basic < 0) return; const duplicate = records.find((item) => item.employeeId === record.employeeId && item.period === record.period && item.id !== editingRecordId); if (duplicate) return alert('A payroll record already exists for this employee and month. Edit the existing snapshot instead.'); const index = records.findIndex((item) => item.id === editingRecordId); record.id = editingRecordId || `PR-${Date.now()}`; record.createdAt = index >= 0 ? records[index].createdAt : new Date().toISOString(); if (index >= 0) records[index] = record; else records.unshift(record); write(RECORD_KEY, records); addAudit(index >= 0 ? 'Edited payroll record' : 'Created payroll record', `${record.employeeName} / ${record.period}`, `Net ${money(totalEarnings(record) - totalDeductions(record))}`); $('record-modal').classList.add('hidden'); renderAll(); }
function advanceRecord(id) { if (!can('approvePayroll')) return alert('Only authorized finance or administrator users can advance workflow status.'); const sequence = ['Draft', 'Under Review', 'Approved', 'Finalized', 'Paid']; const record = records.find((item) => item.id === id); if (!record) return; const next = sequence[Math.min(sequence.indexOf(record.workflowStatus || 'Draft') + 1, sequence.length - 1)]; if (next === record.workflowStatus) return; const previous = record.workflowStatus || 'Draft'; record.workflowStatus = next; if (next === 'Paid') record.paymentStatus = 'Paid'; write(RECORD_KEY, records); addAudit(`Moved payroll to ${next}`, `${record.employeeName} / ${record.period}`, `${previous} → ${next}`); renderAll(); }
function exportCsv() { if (!can('exportReports')) return alert('Your role cannot export reports.'); const rows = [['Period', 'Employee ID', 'Employee', 'Department', 'Gross', 'Deductions', 'Net', 'Workflow', 'Payment']].concat(companySelection().map((record) => [record.period, record.employeeId, record.employeeName, record.department, record.gross, record.deductions, record.net, record.workflowStatus, record.paymentStatus])); const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `payroll-${$('company-period').value || 'report'}.csv`; link.click(); URL.revokeObjectURL(link.href); addAudit('Exported payroll report', $('company-period').value || 'All periods'); }
async function hashPassword(value) { const data = new TextEncoder().encode(value); const hash = await crypto.subtle.digest('SHA-256', data); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
function renderAll() { employees = employeeList(); populateSelects(); renderDashboard(); renderRecords(); renderEmployeeReport(); renderCompanyReport(); renderUsers(); renderAudit(); }

document.querySelectorAll('.nav-tab').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.nav-tab').forEach((item) => item.classList.toggle('active', item === button)); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === `${button.dataset.view}-view`)); }));
$('new-record').addEventListener('click', () => openRecord()); $('record-form').addEventListener('submit', saveRecord); $('new-user').addEventListener('click', () => { if (can('manageUsers')) $('user-modal').classList.remove('hidden'); else alert('Only administrators can manage users.'); }); $('user-form').addEventListener('submit', async (event) => { event.preventDefault(); const email = $('user-email').value.trim().toLowerCase(); if (users.some((user) => user.email === email)) return alert('A user with this email already exists.'); const passwordHash = await hashPassword($('user-password').value); const user = { id: `USR-${Date.now()}`, name: $('user-name').value.trim(), email, department: $('user-department').value.trim(), title: $('user-title').value.trim(), role: $('user-role').value, passwordHash, active: true, createdAt: new Date().toISOString() }; users.unshift(user); write(USER_KEY, users); addAudit('Created user', email, `Role ${user.role}`); $('user-form').reset(); $('user-modal').classList.add('hidden'); renderUsers(); renderAudit(); });
document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => $(button.dataset.close).classList.add('hidden'))); document.querySelectorAll('#dashboard-period,#dashboard-department').forEach((input) => input.addEventListener('input', renderDashboard)); document.querySelectorAll('#record-employee,#record-department,#record-status,#record-payment,#record-from,#record-to,#record-search').forEach((input) => input.addEventListener('input', renderRecords)); document.querySelectorAll('#report-employee,#report-from,#report-to').forEach((input) => input.addEventListener('input', renderEmployeeReport)); document.querySelectorAll('#company-period,#company-department,#company-detail').forEach((input) => input.addEventListener('input', renderCompanyReport)); document.querySelectorAll('#record-form input,#record-form select,#record-form textarea').forEach((input) => input.addEventListener('input', updateFormTotals)); $('print-employee').addEventListener('click', () => window.print()); $('print-company').addEventListener('click', () => window.print()); $('export-csv').addEventListener('click', exportCsv); $('logout').addEventListener('click', () => { localStorage.removeItem('tax-cup-current-role'); localStorage.removeItem('tax-cup-current-user'); window.location.href = 'login.html'; });

if (!users.length) { users = [{ id: 'USR-ADMIN', name: 'Demo administrator', email: 'admin@taxcup.local', department: 'Finance', title: 'System administrator', role: 'Super Administrator', passwordHash: '41bd876b085d6031cb0e04de35b88d77f83a4ba39f879fee40805ac19e356023', active: true, createdAt: new Date().toISOString() }]; write(USER_KEY, users); }
if (!records.length) { const seed = employees.slice(0, 2); records = seed.map((employee, index) => ({ id: `SEED-${employee.id}`, employeeId: employee.id, employeeName: employee.name, department: employee.department, title: employee.title, period: todayMonth(), basic: employee.salary * .5, housing: employee.salary * .2, transport: employee.salary * .15, otherAllowances: employee.salary * .15, bonus: 0, overtime: 0, commission: 0, arrears: 0, otherEarnings: 0, paye: employee.salary * .1, pension: employee.salary * .04, nhf: employee.salary * .0125, loan: 0, advance: 0, otherDeductions: 0, workflowStatus: index ? 'Under Review' : 'Draft', paymentStatus: index ? 'Paid' : 'Pending' })); write(RECORD_KEY, records); }
$('dashboard-period').value = todayMonth(); $('company-period').value = todayMonth(); $('session-user').textContent = currentUser ? `${currentUser.name} / ${currentRole}` : `${currentRole} / local session`; document.querySelectorAll('.admin-only').forEach((item) => item.classList.toggle('hidden', !can('manageUsers'))); renderAll();